### PR TITLE
Adhere to TS and Markdown Style Guidelines

### PR DESCRIPTION
**Pull request by Verisimilitude11**
Makes code easier to read and contribute to. No code changes.

### CODE REVIEW

**Comment by ADawesomeguy** [comment]
Hey, thanks for the PR! What exact guidelines does this modify the code to adhere to?

**Comment by Verisimilitude11** [comment]
https://ts.dev/style/#syntax and https://google.github.io/styleguide/tsguide.html for TypeScript. https://google.github.io/styleguide/docguide/style.html for Markdown.

**Comment by ADawesomeguy** [comment]
Could you please update your branch with the latest commits in `master`?

**Comment by Verisimilitude11** [comment]
Done @ADawesomeguy .

**Comment by ADawesomeguy** [comment]
> Huh looks like ESLint prefers tabs over spaces. That should be an easy fix.
ESLint rules are just some of my personal preferences, if you would like to fix the code to adhere to it you can just run `yarn lint --fix` or `npm run lint --fix`, which in this case is able to fix all the problems.

**Comment by Verisimilitude11** [comment]
> > Huh looks like ESLint prefers tabs over spaces. That should be an easy fix.
> 
> ESLint rules are just some of my personal preferences, if you would like to fix the code to adhere to it you can just run `yarn lint --fix` or `npm run lint --fix`, which in this case is able to fix all the problems.

Could you please git checkout my PR and run ESLint on that and then merge it? I feel like that would be easier to implement as I don't ESLint. Thanks.

**Comment by Verisimilitude11** [comment]
@abheekda1 I pushed some commits that should adhere to the ESLint standard. Could you please verify this? Thanks.

**Comment by abheekda1** [comment]
Running checks. Thank you!

**Review by abheekda1 — APPROVED** [review]

**Pull request merged**
